// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "version", input: never, result: string },
    mutations: 
        { key: "toggle", input: User, result: User },
    subscriptions: 
        { key: "listen_new_user", input: User, result: User }
};

export type User = { mobile: string; more: number; what: boolean[] | null }
