// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "toggle", input: User, result: User } | 
        { key: "version", input: never, result: string },
    mutations: never,
    subscriptions: never
};

export type User = { mobile: string; more: number; what: boolean[] | null }
