// This file is auto-generated by @hey-api/openapi-ts

export const $SendCode = {
    type: 'object',
    properties: {
        mobile: {
            type: 'string'
        }
    },
    required: ['mobile']
} as const;

export const $SendCodeResponse = {
    type: 'object',
    properties: {
        found_account: {
            type: 'boolean'
        }
    },
    required: ['found_account']
} as const;