// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { SendCodeData, SendCodeError, SendCodeResponse2, SendCode2Data, SendCode2Error, SendCode2Response } from './types.gen';

export const client = createClient(createConfig());

export const sendCode = <ThrowOnError extends boolean = false>(options: Options<SendCodeData, ThrowOnError>) => { return (options?.client ?? client).post<SendCodeResponse2, SendCodeError, ThrowOnError>({
    ...options,
    url: '/send-code'
}); };

export const sendCode2 = <ThrowOnError extends boolean = false>(options: Options<SendCode2Data, ThrowOnError>) => { return (options?.client ?? client).post<SendCode2Response, SendCode2Error, ThrowOnError>({
    ...options,
    url: '/send-code2/{some_path_what}'
}); };