// This file is auto-generated by @hey-api/openapi-ts

export type SendCode = {
    mobile: string;
};

export type SendCodeResponse = {
    found_account: boolean;
};

export type SendCodeData = {
    body: SendCode;
};

export type SendCodeResponse2 = SendCodeResponse;

export type SendCodeError = unknown;

export type SendCode2Data = {
    body: SendCode;
    path?: {
        some_path_what?: string;
    };
};

export type SendCode2Response = SendCode;

export type SendCode2Error = unknown;