[package]
name = "server2"
version = "0.1.0"
edition = "2021"

[dependencies]
poem = "3.0.4"
poem-openapi = { version = "5.0.3", features = ["swagger-ui"] }
serde = "1.0.207"
serde_json = "1.0.124"
tokio = { version = "1.9.0", features = ["macros", "rt-multi-thread", "sync"] }
